package org.gdgsantodomingo.apec.android.devfestapec.service;

public class GithubServiceSetupData {
    public static final String ERROR_RESPONSE = "{\n"
                                                + "\"message\": \"Not Found\",\n"
                                                + "\"documentation_url\": \"https://developer.github.com/v3\"\n"
                                                + "}";

    public static final String VALID_RESPONSE_WITHOUT_FOLLOWERS = "[]\n";

    public static final String VALID_RESPONSE_WITH_FOLLOWERS = "[\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"myhduck\",\n"
                                                               + "    \"id\": 1555350,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/1555350?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/myhduck\",\n"
                                                               + "    \"html_url\": \"https://github.com/myhduck\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/myhduck/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/myhduck/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/myhduck/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/myhduck/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/myhduck/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/myhduck/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/myhduck/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/myhduck/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/myhduck/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"trevor\",\n"
                                                               + "    \"id\": 5945,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/5945?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/trevor\",\n"
                                                               + "    \"html_url\": \"https://github.com/trevor\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/trevor/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/trevor/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/trevor/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/trevor/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/trevor/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/trevor/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/trevor/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/trevor/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/trevor/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"ogijun\",\n"
                                                               + "    \"id\": 8826,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/8826?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/ogijun\",\n"
                                                               + "    \"html_url\": \"https://github.com/ogijun\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/ogijun/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/ogijun/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/ogijun/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/ogijun/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/ogijun/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/ogijun/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/ogijun/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/ogijun/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/ogijun/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"mattn\",\n"
                                                               + "    \"id\": 10111,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/10111?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/mattn\",\n"
                                                               + "    \"html_url\": \"https://github.com/mattn\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/mattn/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/mattn/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/mattn/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/mattn/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/mattn/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/mattn/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/mattn/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/mattn/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/mattn/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"reeze\",\n"
                                                               + "    \"id\": 14658,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/14658?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/reeze\",\n"
                                                               + "    \"html_url\": \"https://github.com/reeze\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/reeze/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/reeze/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/reeze/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/reeze/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/reeze/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/reeze/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/reeze/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/reeze/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/reeze/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"othree\",\n"
                                                               + "    \"id\": 16474,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/16474?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/othree\",\n"
                                                               + "    \"html_url\": \"https://github.com/othree\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/othree/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/othree/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/othree/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/othree/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/othree/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/othree/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/othree/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/othree/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/othree/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"rkh\",\n"
                                                               + "    \"id\": 30442,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/30442?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/rkh\",\n"
                                                               + "    \"html_url\": \"https://github.com/rkh\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/rkh/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/rkh/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/rkh/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/rkh/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/rkh/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/rkh/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/rkh/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/rkh/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/rkh/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"keikubo\",\n"
                                                               + "    \"id\": 42560,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/42560?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/keikubo\",\n"
                                                               + "    \"html_url\": \"https://github.com/keikubo\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/keikubo/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/keikubo/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/keikubo/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/keikubo/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/keikubo/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/keikubo/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/keikubo/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/keikubo/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/keikubo/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"cobra90nj\",\n"
                                                               + "    \"id\": 42698,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/42698?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/cobra90nj\",\n"
                                                               + "    \"html_url\": \"https://github.com/cobra90nj\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/cobra90nj/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/cobra90nj/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/cobra90nj/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/cobra90nj/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/cobra90nj/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/cobra90nj/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/cobra90nj/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/cobra90nj/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/cobra90nj/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"jdoliner\",\n"
                                                               + "    \"id\": 43867,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/43867?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/jdoliner\",\n"
                                                               + "    \"html_url\": \"https://github.com/jdoliner\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/jdoliner/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/jdoliner/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/jdoliner/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/jdoliner/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/jdoliner/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/jdoliner/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/jdoliner/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/jdoliner/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/jdoliner/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"tatsuo\",\n"
                                                               + "    \"id\": 44219,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/44219?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/tatsuo\",\n"
                                                               + "    \"html_url\": \"https://github.com/tatsuo\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/tatsuo/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/tatsuo/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/tatsuo/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/tatsuo/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/tatsuo/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/tatsuo/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/tatsuo/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/tatsuo/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/tatsuo/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"shimbaco\",\n"
                                                               + "    \"id\": 56767,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/56767?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/shimbaco\",\n"
                                                               + "    \"html_url\": \"https://github.com/shimbaco\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/shimbaco/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/shimbaco/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/shimbaco/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/shimbaco/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/shimbaco/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/shimbaco/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/shimbaco/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/shimbaco/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/shimbaco/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"catsby\",\n"
                                                               + "    \"id\": 61721,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/61721?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/catsby\",\n"
                                                               + "    \"html_url\": \"https://github.com/catsby\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/catsby/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/catsby/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/catsby/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/catsby/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/catsby/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/catsby/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/catsby/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/catsby/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/catsby/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"lrvick\",\n"
                                                               + "    \"id\": 69200,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/69200?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/lrvick\",\n"
                                                               + "    \"html_url\": \"https://github.com/lrvick\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/lrvick/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/lrvick/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/lrvick/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/lrvick/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/lrvick/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/lrvick/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/lrvick/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/lrvick/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/lrvick/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"InFog\",\n"
                                                               + "    \"id\": 72276,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/72276?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/InFog\",\n"
                                                               + "    \"html_url\": \"https://github.com/InFog\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/InFog/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/InFog/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/InFog/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/InFog/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/InFog/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/InFog/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/InFog/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/InFog/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/InFog/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"Sannis\",\n"
                                                               + "    \"id\": 77367,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/77367?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/Sannis\",\n"
                                                               + "    \"html_url\": \"https://github.com/Sannis\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/Sannis/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/Sannis/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/Sannis/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/Sannis/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/Sannis/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/Sannis/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/Sannis/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/Sannis/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/Sannis/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"nolim1t\",\n"
                                                               + "    \"id\": 83470,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/83470?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/nolim1t\",\n"
                                                               + "    \"html_url\": \"https://github.com/nolim1t\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/nolim1t/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/nolim1t/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/nolim1t/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/nolim1t/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/nolim1t/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/nolim1t/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/nolim1t/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/nolim1t/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/nolim1t/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"moul\",\n"
                                                               + "    \"id\": 94029,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/94029?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/moul\",\n"
                                                               + "    \"html_url\": \"https://github.com/moul\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/moul/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/moul/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/moul/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/moul/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/moul/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/moul/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/moul/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/moul/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/moul/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"bx2\",\n"
                                                               + "    \"id\": 94500,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/94500?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/bx2\",\n"
                                                               + "    \"html_url\": \"https://github.com/bx2\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/bx2/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/bx2/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/bx2/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/bx2/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/bx2/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/bx2/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/bx2/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/bx2/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/bx2/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"pitr\",\n"
                                                               + "    \"id\": 102791,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/102791?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/pitr\",\n"
                                                               + "    \"html_url\": \"https://github.com/pitr\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/pitr/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/pitr/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/pitr/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/pitr/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/pitr/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/pitr/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/pitr/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/pitr/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/pitr/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"JoseRibeiro\",\n"
                                                               + "    \"id\": 108473,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/108473?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/JoseRibeiro\",\n"
                                                               + "    \"html_url\": \"https://github.com/JoseRibeiro\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/JoseRibeiro/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/JoseRibeiro/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/JoseRibeiro/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/JoseRibeiro/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/JoseRibeiro/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/JoseRibeiro/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/JoseRibeiro/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/JoseRibeiro/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/JoseRibeiro/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"dpflug\",\n"
                                                               + "    \"id\": 108501,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/108501?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/dpflug\",\n"
                                                               + "    \"html_url\": \"https://github.com/dpflug\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/dpflug/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/dpflug/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/dpflug/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/dpflug/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/dpflug/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/dpflug/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/dpflug/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/dpflug/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/dpflug/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"kennethreitz\",\n"
                                                               + "    \"id\": 119893,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/119893?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/kennethreitz\",\n"
                                                               + "    \"html_url\": \"https://github.com/kennethreitz\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/kennethreitz/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/kennethreitz/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/kennethreitz/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/kennethreitz/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/kennethreitz/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/kennethreitz/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/kennethreitz/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/kennethreitz/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/kennethreitz/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"danielrmz\",\n"
                                                               + "    \"id\": 120647,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/120647?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/danielrmz\",\n"
                                                               + "    \"html_url\": \"https://github.com/danielrmz\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/danielrmz/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/danielrmz/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/danielrmz/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/danielrmz/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/danielrmz/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/danielrmz/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/danielrmz/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/danielrmz/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/danielrmz/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"vitaminjeff\",\n"
                                                               + "    \"id\": 125537,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/125537?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/vitaminjeff\",\n"
                                                               + "    \"html_url\": \"https://github.com/vitaminjeff\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/vitaminjeff/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/vitaminjeff/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/vitaminjeff/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/vitaminjeff/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/vitaminjeff/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/vitaminjeff/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/vitaminjeff/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/vitaminjeff/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/vitaminjeff/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"chrisforbes\",\n"
                                                               + "    \"id\": 128877,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/128877?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/chrisforbes\",\n"
                                                               + "    \"html_url\": \"https://github.com/chrisforbes\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/chrisforbes/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/chrisforbes/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/chrisforbes/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/chrisforbes/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/chrisforbes/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/chrisforbes/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/chrisforbes/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/chrisforbes/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/chrisforbes/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"axiomsofchoice\",\n"
                                                               + "    \"id\": 136502,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/136502?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/axiomsofchoice\",\n"
                                                               + "    \"html_url\": \"https://github.com/axiomsofchoice\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/axiomsofchoice/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/axiomsofchoice/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/axiomsofchoice/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/axiomsofchoice/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/axiomsofchoice/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/axiomsofchoice/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/axiomsofchoice/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/axiomsofchoice/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/axiomsofchoice/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"EnTeQuAk\",\n"
                                                               + "    \"id\": 139033,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/139033?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/EnTeQuAk\",\n"
                                                               + "    \"html_url\": \"https://github.com/EnTeQuAk\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/EnTeQuAk/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/EnTeQuAk/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/EnTeQuAk/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/EnTeQuAk/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/EnTeQuAk/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/EnTeQuAk/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/EnTeQuAk/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/EnTeQuAk/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/EnTeQuAk/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"jag\",\n"
                                                               + "    \"id\": 162375,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/162375?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/jag\",\n"
                                                               + "    \"html_url\": \"https://github.com/jag\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/jag/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/jag/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/jag/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/jag/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/jag/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/jag/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/jag/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/jag/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/jag/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  },\n"
                                                               + "  {\n"
                                                               + "    \"login\": \"cebe\",\n"
                                                               + "    \"id\": 189796,\n"
                                                               + "    \"avatar_url\": \"https://avatars.githubusercontent.com/u/189796?v=3\",\n"
                                                               + "    \"gravatar_id\": \"\",\n"
                                                               + "    \"url\": \"https://api.github.com/users/cebe\",\n"
                                                               + "    \"html_url\": \"https://github.com/cebe\",\n"
                                                               + "    \"followers_url\": \"https://api.github.com/users/cebe/followers\",\n"
                                                               + "    \"following_url\": \"https://api.github.com/users/cebe/following{/other_user}\",\n"
                                                               + "    \"gists_url\": \"https://api.github.com/users/cebe/gists{/gist_id}\",\n"
                                                               + "    \"starred_url\": \"https://api.github.com/users/cebe/starred{/owner}{/repo}\",\n"
                                                               + "    \"subscriptions_url\": \"https://api.github.com/users/cebe/subscriptions\",\n"
                                                               + "    \"organizations_url\": \"https://api.github.com/users/cebe/orgs\",\n"
                                                               + "    \"repos_url\": \"https://api.github.com/users/cebe/repos\",\n"
                                                               + "    \"events_url\": \"https://api.github.com/users/cebe/events{/privacy}\",\n"
                                                               + "    \"received_events_url\": \"https://api.github.com/users/cebe/received_events\",\n"
                                                               + "    \"type\": \"User\",\n"
                                                               + "    \"site_admin\": false\n"
                                                               + "  }\n"
                                                               + "]\n";
}
